### ISSUE TITLE
linter-gcc2 doesn't see multiple headers.And linter-gcc, too!

### ISSUE THREAD

**Issue by Otavva** [tvincent056/linter-gcc2#7]
## Issue (including debugging messages):
Hi! I tried to use linter-gcc2 and it was good at first. But when I included headers like showed down I get error: header.h: no such file. At first I thougth that this is my error or error of linter-gcc2. But programm compile. And when I installed linter 2.2.0 and linter-gcc from hiebashi I sow that there is no more error. So I'll use hiebashi's linter-gcc because of in the real projects you need to connect many headers in headers.

`//main.cpp`
`#include "headera.h"`
`#include "headerb.h"`
`/*code*/`

`//headera.h`
`#ifndef HEADA_H`
`#define HEADA_H` 
`/*code*/"`
`#endif `

`//headerb.h`
`#include "headerb.h"`
`/*code*/`

Thank you for your time!

**Comment by tvincent056** [comment]
@Otavva There should be no reason linter-gcc2 does not work for such a setup. I have been using it with massively complex projects with many different header include schemes with no problem. The module actually uses the g++ compiler to generate error messages, so either your configuration is incorrect, or there is a problem in the linter-gcc2 module as it relays the information between atom and g++. 

Could you give me some more detail? Are you using compile_commands.json, .gcc-flags.json, or did you just enter values in the settings menu?

**Comment by Otavva** [comment]
Oops. There is error in the linter-gcc too. I thought this was fixed due to [this](https://github.com/hebaishi/linter-gcc/issues/39) thread. And this has been fixed, but not now. I just turn on lint on fly, like man from thread. But there is no error when lint on fly turned off. By the way in the thread error based on lint on fly, too.

_Sorry for quality of the gif's_

![2019-02-16-08-06-50](https://user-images.githubusercontent.com/38220344/52895489-ec0a6a00-31c3-11e9-98ad-0f49c32c79b9.gif)

Programm compile good.

![2019-02-16-08-13-32](https://user-images.githubusercontent.com/38220344/52895496-05131b00-31c4-11e9-88e7-d10ca516e352.gif)


P.S. Sorry if I sayed something wrong. I'm not native English speaker. By the way wy when I saving header with linter-gcc2 they saving and add .gch (precompiled header)? I don't needed it.

**Comment by tvincent056** [comment]
It looks like you found an interesting flaw that only applies when you are trying to build without using include paths (e.g. -I or -isystem options). As noted in [this article](https://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art026), the cpp pre-processor has an implicit search path for include files (only ones specified using quotes, e.g. #include "file.h") in the parent directory of the file being compiled. When you enable Linter-on-the-fly, a temporary file is created in a different place in the background to perform the linting. Since the parent directory is not the same, it cannot find the include files that would normally be found with that implicit search path. To fix this, I have now added an "-iquote" search path to the compile command when Lint-on-the-fly is enabled.
