### ISSUE TITLE
'complex' does not name a type

### ISSUE THREAD

**Issue by crswong888** [tvincent056/linter-gcc2#9]
Hello, I am using a C library `complex.h` which allows the use of the `complex` data type, like a double or a float, in my C code. I am compiling just fine, so this is not a real issue, but for some reason linter-gcc2 is thinking that it is one. Here's a snapshot of my screen so you it can be visualized what is happening:

![Screenshot from 2019-03-26 15-52-15](https://user-images.githubusercontent.com/41302548/55028972-60180900-4fdf-11e9-8c8e-135e4b719031.png)

I have a feeling there might simply be something in my package settings that might make this work, but I'm not sure. Any advice for how I can fix this? Maybe this is a real bug?

**Comment by tvincent056** [comment]
The issue appears to be that linter-gcc2 is using the g++ command instead of gcc to check your code. For whatever reason, the original designer of linter-gcc chose to make g++ the default for everything. You can change it manually in the settings page under "GCC Executable Path" or by creating a compile_commands.json file or .gcc-flags.json file. If you think it would be useful, it probably wouldn't be too much trouble for me to add separate defaults for C and C++ language types as well.

**Comment by crswong888** [comment]
Yes, you are right! I simply changed my GCC executable path to the proper directory and it solved this issue with the `complex` type. I don't think that it is totally necessary that you changed the defaults, because I've been using this linter for awhile now and this was the first time I've had this issue, so for the most part the default compiler for C has worked fine. And at least, for my special case, I've been able to solve this problem by changing the settings.

Thanks for your help, I should be all set now!
